---
apiVersion: v1
kind: ConfigMap
metadata:
  name: quannguyen1999-configmap
data:
  SPRING_PROFILES_ACTIVE: dev
  SPRING_CONFIG_IMPORT: configserver:http://shopee-be-config-demo:8071/
  SPRING_FLYWAY_URL: jdbc:postgresql://postgres-shopee:5431/postgres?currentSchema=qa_shopee
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-shopee:5431/postgres?currentSchema=qa_shopee
  SPRING_RABBITMQ_HOST: rabbitmq
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI: http://shopee-be-account-demo:8070

  ACCOUNT_APPLICATION_NAME: account
  ADMIN_APPLICATION_NAME: admin
  CONFIG_APPLICATION_NAME: shopee-be-config-demo
  EUREKA_APPLICATION_NAME: eureka
  GATEWAY_APPLICATION_NAME: gateway
  EMAIL_APPLICATION_NAME: email

  CUSTOM-SECURITY_ISSUER: http://shopee-be-account-demo:8070
  CUSTOM_SECURITY_OAUTH2URL: http://shopee-be-account-demo:8070
  CUSTOM_EMAIL_URL: http://shopee-be-email-demo:9000
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://shopee-be-eureka-demo:8072/eureka/

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-secret
  labels:
    app: postgres-shopee
data:
  POSTGRES_DB: qa_shopee
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres