apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopee-be-admin-demo
  labels:
    app: shopee-be-admin-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopee-be-admin-demo
  template:
    metadata:
      labels:
        app: shopee-be-admin-demo
    spec:
      containers:
        - name: shopee-be-admin-demo
          image: quannguyen1999/shopee-be-admin-demo
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_APPLICATION_NAME
              valueFrom:
                configMapKeyRef:
                  name: quannguyen1999-configmap
                  key: ADMIN_APPLICATION_NAME
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: quannguyen1999-configmap
                  key: SPRING_PROFILES_ACTIVE
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: quannguyen1999-configmap
                  key: SPRING_CONFIG_IMPORT
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: quannguyen1999-configmap
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: quannguyen1999-configmap
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_FLYWAY_URL
              valueFrom:
                configMapKeyRef:
                  name: quannguyen1999-configmap
                  key: SPRING_FLYWAY_URL
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI
              valueFrom:
                configMapKeyRef:
                  name: quannguyen1999-configmap
                  key: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI
            - name: CUSTOM-SECURITY_ISSUER
              valueFrom:
                configMapKeyRef:
                  name: quannguyen1999-configmap
                  key: CUSTOM-SECURITY_ISSUER
            - name: CUSTOM_SECURITY_OAUTH2URL
              valueFrom:
                configMapKeyRef:
                  name: quannguyen1999-configmap
                  key: CUSTOM_SECURITY_OAUTH2URL
            - name: CUSTOM_EMAIL_URL
              valueFrom:
                configMapKeyRef:
                  name: quannguyen1999-configmap
                  key: CUSTOM_EMAIL_URL
---
apiVersion: v1
kind: Service
metadata:
  name: shopee-be-admin-demo
spec:
  selector:
    app: shopee-be-admin-demo
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
