#Spring doc
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

#MyBatis
mybatis:
  mapper-locations: classpath:batis/*.xml
  type-aliases-package: com.shopee.shopeebeadmindemo.mybatis
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#Config Eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
info:
  app:
    name: "admins"
    description: "Shopee be admin demo"
    version: "1.0.0"

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000



