spring:
  application:
    name: shopee-be-config-demo
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-location: "classpath:/config/**"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
server:
  port: 8071