{{- define "common.deployment" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploymentName }}
  labels:
    app: {{ .Values.appLabel }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.appLabel }}
    spec:
      containers:
      - name: {{ .Values.appLabel }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Never
        ports:
        - containerPort: {{ .Values.containerPort }}
          protocol: TCP
        env:
        {{- if .Values.appname_enabled }}
        - name: SPRING_APPLICATION_NAME
          value: {{ .Values.appName }}
        {{- end }}
        {{- if .Values.profile_enabled }}
        - name: SPRING_PROFILES_ACTIVE
          valueFrom: 
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: SPRING_PROFILES_ACTIVE
        {{- end }}
        {{- if .Values.config_enabled }}
        - name: SPRING_CONFIG_IMPORT
          valueFrom: 
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: SPRING_CONFIG_IMPORT
        {{- end }}
        {{- if .Values.eureka_enabled }}
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          valueFrom: 
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        {{- end }}
        {{ - if .Values.springDataSourceEnabled }}
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: { { .Values.global.configMapName } }
              key: SPRING_DATASOURCE_URL
        {{ - end }}
        {{ - if .Values.springFlywayUrlEnabled }}
        - name: SPRING_FLYWAY_URL
          valueFrom:
            configMapKeyRef:
              name: { { .Values.global.configMapName } }
              key: SPRING_FLYWAY_URL
        {{ - end }}
        {{ - if .Values.securityIssuerEnabled }}
        - name: CUSTOM-SECURITY_ISSUER
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: CUSTOM-SECURITY_ISSUER
        {{ - end }}
        {{ - if .Values.springSecurityOauth2IssuerUriEnabled }}
        - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI
        {{ - end }}
        { { - if .Values.customSecurityOauth2UrlEnabled } }
        - name: CUSTOM_SECURITY_OAUTH2URL
          valueFrom:
            configMapKeyRef:
              name: { { .Values.global.configMapName } }
              key: CUSTOM_SECURITY_OAUTH2URL
        { { - end } }
        { { - if .Values.customEmailUrlEnabled } }
        - name: CUSTOM_EMAIL_URL
          valueFrom:
            configMapKeyRef:
              name: { { .Values.global.configMapName } }
              key: CUSTOM_EMAIL_URL
        { { - end } }
        { { - if .Values.springRabbitmqHostEnabled } }
        - name: SPRING_RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: { { .Values.global.configMapName } }
              key: SPRING_RABBITMQ_HOST
        { { - end } }


{{- end -}}