services:
  #RabbitMQ
  rabbit:
    image: rabbitmq:management
    container_name: rabbit
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - type: bind
        source: ../data/rabbitmq
        target: /var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s
    extends:
      file: common-config.yml
      service: network-deploy-service

  redis-shopee:
    image: redis
    container_name: redis-shopee
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL","redis-cli ping | grep PONG"]
      timeout: 10s
      retries: 10
    extends:
      file: common-config.yml
      service: network-deploy-service

  postgres-shopee:
    image: postgres
    container_name: postgres-shopee
    ports:
      - "5431:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    extends:
      file: common-config.yml
      service: network-deploy-service

  shopee-be-config-demo:
    image: "quannguyen1999/shopee-be-config-demo"
    container_name: shopee-be-config-demo
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  shopee-be-eureka-demo:
    image: "quannguyen1999/shopee-be-eureka-demo"
    container_name: shopee-be-eureka-demo
    ports:
      - "8072:8072"
    healthcheck:
      test: "curl --fail --silent localhost:8072/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-config-eureka-config

  shopee-be-gateway-demo:
    image: "quannguyen1999/shopee-be-gateway-demo"
    container_name: shopee-be-gateway-demo
    ports:
      - "8073:8073"
    depends_on:
      shopee-be-admin-demo:
        condition: service_healthy
      shopee-be-email-demo:
        condition: service_healthy
      redis-shopee:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-config-eureka-config

  shopee-be-account-demo:
    image: "quannguyen1999/shopee-be-account-demo"
    container_name: shopee-be-account-demo
    ports:
      - "8070:8070"
    extends:
      file: common-config.yml
      service: microservice-config-server-config

  shopee-be-admin-demo:
    image: "quannguyen1999/shopee-be-admin-demo"
    container_name: shopee-be-admin-demo
    ports:
      - "8080:8080"
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_RABBITMQ_HOST: "rabbit"
    extends:
      file: common-config.yml
      service: microservice-config-server-config

  shopee-be-email-demo:
    image: "quannguyen1999/shopee-be-email-demo"
    container_name: shopee-be-email-demo
    ports:
      - "9000:9000"
    healthcheck:
      test: "curl --fail --silent localhost:9000/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      rabbit:
        condition: service_healthy
    environment:
      SPRING_RABBITMQ_HOST: "rabbit"
    extends:
      file: common-config.yml
      service: microservice-config-email

networks:
  shopee-network:
    driver: "bridge"


