services:
  postgres-shopee:
    image: postgres
    container_name: postgres-shopee
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres

  config:
    image: "quannguyen1999/shopee-be-config-demo:0.0.1-SNAPSHOT"
    container_name: shopee-be-config-demo
    ports:
      - "8071:8071"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - shopee-network

  accounts:
    image: "quannguyen1999/shopee-be-account-demo:0.0.1-SNAPSHOT"
    container_name: shopee-be-account-demo
    ports:
      - "8070:8070"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - shopee-network

  admin:
    image: "quannguyen1999/shopee-be-admin-demo:0.0.1-SNAPSHOT"
    container_name: shopee-be-admin-demo
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - shopee-network

networks:
  shopee-network:
    driver: "bridge"

