services:
  network-deploy-service:
    networks:
      - "shopee-network"
  microservice-base-config:
    extends: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      JAVA_TOOL_OPTIONS: "-javaagent:/app/libs/opentelemetry-javaagent-1.32.0.jar"
      OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo:4317
      OTEL_METRICS_EXPORTER: none
  microservice-config-server-config:
    extends:
      service: microservice-base-config
    depends_on:
      shopee-be-config-demo:
        condition: service_healthy
      shopee-be-eureka-demo:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://shopee-be-config-demo:8071/
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-shopee:5432/postgres?currentSchema=qa_shopee
      SPRING_FLYWAY_URL: jdbc:postgresql://postgres-shopee:5432/postgres?currentSchema=qa_shopee
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI: http://shopee-be-account-demo:8070
      CUSTOM-SECURITY_ISSUER: http://shopee-be-account-demo:8070
      CUSTOM_SECURITY_OAUTH2URL: http://shopee-be-account-demo:8070
      CUSTOM_EMAIL_URL: http://shopee-be-email-demo:9000
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://shopee-be-eureka-demo:8072/eureka/

  microservice-config-eureka-config:
    extends:
      service: microservice-base-config
    depends_on:
      shopee-be-config-demo:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://shopee-be-config-demo:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://shopee-be-eureka-demo:8072/eureka/

  microservice-config-email:
    extends: microservice-config-eureka-config
    environment:
      SPRING_RABBITMQ_HOST: rabbit


